export const achievementData = [
  {
    id: 1,
    title: "AI/ML Stage 01",
    status: "Completed",
    year: "2026",
    description: "Focuses on developing core AI/ML skills for real-world industry use.",
    university: "SLIIT",
  }, {
    id: 2,
    title: "AI/ML Stage 02",
    status: "In Progress",
    year: "",
    description: "Focuses on supervised learning techniques for solving real-world AI problems.",
    university: "SLIIT",
  }, {
    id: 3,
    title: "AI/ML Stage 03",
    status: "Not Started",
    year: "",
    description: "Focuses on unsupervised learning techniques for solving real-world AI problems.",
    university: "SLIIT",
  }, {
    id: 4,
    title: "AI/ML Stage 04",
    status: "Not Started",
    year: "",
    description: "Focuses on supervised learning techniques for solving real-world AI problems.",
    university: "SLIIT",
  }, {
    id: 5,
    title: "AI/ML Stage 01",
    status: "Completed",
    year: "2026",
    description: "Focuses on developing core AI/ML skills for real-world industry use.",
    university: "SLIIT",
  }, {
    id: 6,
    title: "AI/ML Stage 02",
    status: "In Progress",
    year: "",
    description: "Focuses on supervised learning techniques for solving real-world AI problems.",
    university: "SLIIT",
  }, {
    id: 5,
    title: "AI/ML Stage 01",
    status: "Completed",
    year: "2026",
    description: "Focuses on developing core AI/ML skills for real-world industry use.",
    university: "SLIIT",
  }, {
    id: 6,
    title: "AI/ML Stage 02",
    status: "In Progress",
    year: "",
    description: "Focuses on supervised learning techniques for solving real-world AI problems.",
    university: "SLIIT",
  }, {
    id: 5,
    title: "AI/ML Stage 01",
    status: "Completed",
    year: "2026",
    description: "Focuses on developing core AI/ML skills for real-world industry use.",
    university: "SLIIT",
  }, {
    id: 6,
    title: "AI/ML Stage 02",
    status: "In Progress",
    year: "",
    description: "Focuses on supervised learning techniques for solving real-world AI problems.",
    university: "SLIIT",
  }
];